"""Add Journal

Revision ID: 937a2769820e
Revises: 6c72301ade5c
Create Date: 2026-08-23 22:40:12.884692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937a2769820e'
down_revision: Union[str, Sequence[str], None] = '6c72301ade5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal')
    # ### end Alembic commands ###
